const data = [
    {
        id: 's-1',
        key: "shoe-1",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-2',
        key: "shoe-2",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-3',
        key: "shoe-3",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-4',
        key: "shoe-4",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-5',
        key: "shoe-5",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-6',
        key: "shoe-6",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-7',
        key: "shoe-7",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-8',
        key: "shoe-8",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-9',
        key: "shoe-9",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-10',
        key: "shoe-10",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-11',
        key: "shoe-11",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    },
    {
        id: 's-12',
        key: "shoe-12",
        name: "",
        product_description: "",
        price: '',
        product_thumbnail: '',
        brand_name: '',
        product_size: '',
        product_stock: '',
    }
]